15 TZ
babkaizergil/java-shareit pull request #3
Opened 2023-07-16 13:36 UTC by babkaizergil

2023-07-16 21:23 UTC, babkaizergil commented
Доброго времени суток. Тесты постмана все проходят. Нужна помощь, в упор не вижу почему не получаются некоторые тесты. Не понимаю почему не создаются репозитории, хотя явно прописываю beforeEach, например. Или почему я отлавливаю 500 ошибку класса Throwable по замечанию прошлого ТЗ, но не могу перехватить 400, когда не верные параметры метода.

2023-07-17 20:55 UTC, Donald522 commented
> Доброго времени суток. Тесты постмана все проходят. Нужна помощь, в упор не вижу почему не получаются некоторые тесты. Не понимаю почему не создаются репозитории, хотя явно прописываю beforeEach, например. Или почему я отлавливаю 500 ошибку класса Throwable по замечанию прошлого ТЗ, но не могу перехватить 400, когда не верные параметры метода.

Чтобы перехватить 400 из-за неверного json, надо явно прописывать хэндлер для исключения jackson-а. Навскидку не помню точное название, поищи. Так происходит, потому что спринг не может найти обработчик для этого исключения и берет обработчик для ближайшего родителя.

2023-07-21 23:31 UTC, babkaizergil commented
Прошу помощи. Я в упор не понимаю, почему в тестах не находится юзер0. когда он явно beforeEach создается. Пожалуйста, объясните.

2023-07-22 15:03 UTC, Donald522 requested changes
Привет!

Я не совсем понимаю вопрос про тесты и что конкретно там не работает.
Могу посоветовать обратиться к наставнику, если не получается написать тест. Если наставник не сможет помочь, тогда можешь написать мне в ЛС, только с подробным объяснением проблемы.

2023-07-24 17:24 UTC, Donald522 approved these changes

2023-07-25 06:47 UTC, merged