16 TZ Add docker
babkaizergil/java-shareit pull request #4
Opened 2023-07-25 06:55 UTC by babkaizergil

Здравствуй, уважаемый ревьюер!) попытка запрыгнуть в последний вагон.

2023-07-25 19:18 UTC, Donald522 requested changes
Привет!

По коду замечания написал.
Насчет тестов - пишет, что покрытия не хватает. 
В любом случае, с этим вопрос рекомендую обратиться к наставнику.

2023-07-25 19:18 UTC, Donald522 commented on docker-compose.yaml
> +    volumes:
Вот это точно нужно?
Какой путь по умолчанию и почему он не подходит?

2023-07-25 19:18 UTC, Donald522 commented on docker-compose.yaml
> +      - POSTGRES_USER=test
Хорошей практикой считается называть пользователя именем приложения.
Удобно потом смотреть кто держит подключения к базе, наприер

2023-07-25 19:18 UTC, Donald522 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
В сервере нам валидация больше не нужна, мы ее перенесли в гейтвэй

2023-07-25 19:18 UTC, Donald522 commented on gateway/src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +//    @ExceptionHandler(Throwable.class)
Этот хэндлер обязательно нужен

2023-07-29 08:53 UTC, babkaizergil commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
убрала

2023-07-29 08:54 UTC, babkaizergil commented on gateway/src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +//    @ExceptionHandler(Throwable.class)
раскомментировала

2023-07-31 13:59 UTC, babkaizergil commented on docker-compose.yaml
> +      - POSTGRES_USER=test
поправила

2023-08-02 10:44 UTC, closed without merging